### ISSUE TITLE
Web UI: matched license text display seems off by one line

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#292] opened 2021-08-18 08:27 UTC
In https://github.com/petiaccja/Mathter/archive/04653b39611cfae935aecd8e036106a6ce5bef0a.zip  the attached file 
[_decompose_l_u_8hpp_source.txt](https://github.com/nexB/scancode.io/files/7005722/_decompose_l_u_8hpp_source.txt)
has its license matches off by one line... I highlighted in blue the part that should have been shown

![Screenshot from 2021-08-18 10-26-48](https://user-images.githubusercontent.com/675997/129864842-a8541ebd-9a35-4ef8-bc4d-67f525bb383d.png)

**Comment by tdruez** [comment] 2021-08-18 09:11
@pombredanne this looks like an issue on the toolkit side, `"start_line": 70` and `"end_line": 70`

```
{
    "key": "unknown-license-reference",
    "name": "Unknown License file reference",
    "owner": "Unspecified",
    "score": 11.0,
    "policy": {
        "icon": "fas fa-exclamation-triangle",
        "label": "Restricted License",
        "color_code": "#ffcc33",
        "license_key": "unknown-license-reference",
        "compliance_alert": "warning",
    },
    "category": "Unstated License",
    "end_line": 70,
    "spdx_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/unknown-license-reference.LICENSE",
    "text_url": "",
    "short_name": "Unknown License reference",
    "start_line": 70,
    "homepage_url": None,
    "is_exception": False,
    "matched_rule": {
        "matcher": "2-aho",
        "licenses": ["unknown-license-reference"],
        "identifier": "license-intro_9.RULE",
        "rule_length": 2,
        "is_license_tag": False,
        "match_coverage": 100.0,
        "matched_length": 2,
        "rule_relevance": 11,
        "is_license_text": False,
        "is_license_intro": True,
        "is_license_notice": False,
        "license_expression": "unknown-license-reference",
        "is_license_reference": False,
    },
    "matched_text": "distributed under",
    "reference_url": "https://scancode-licensedb.aboutcode.org/unknown-license-reference",
    "spdx_license_key": "LicenseRef-scancode-unknown-license-reference",
    "scancode_data_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/unknown-license-reference.yml",
    "scancode_text_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/unknown-license-reference.LICENSE",
}
```

**Comment by tdruez** [comment] 2021-08-18 09:45
```
$ scancode --json-pp - --license --package _decompose_l_u_8hpp_source.html
```

```
Setup plugins...
Collect file inventory...
Scan files for: licenses, packages with 1 process(es)...

{
  "headers": [
    {
      "tool_name": "scancode-toolkit",
      "tool_version": "21.8.4",
      "options": {
        "input": [
          "_decompose_l_u_8hpp_source.html"
        ],
        "--json-pp": "-",
        "--license": true,
        "--package": true
      },
      "notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "start_timestamp": "2021-08-18T094235.391697",
      "end_timestamp": "2021-08-18T094237.811415",
      "duration": 2.419769048690796,
      "message": null,
      "errors": [],
      "extra_data": {
        "files_count": 1
      }
    }
  ],
  "files": [
    {
      "path": "_decompose_l_u_8hpp_source.html",
      "type": "file",
      "licenses": [
        {
          "key": "unknown-license-reference",
          "score": 11.0,
          "name": "Unknown License file reference",
          "short_name": "Unknown License reference",
          "category": "Unstated License",
          "is_exception": false,
          "owner": "Unspecified",
          "homepage_url": null,
          "text_url": "",
          "reference_url": "https://scancode-licensedb.aboutcode.org/unknown-license-reference",
          "scancode_text_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/unknown-license-reference.LICENSE",
          "scancode_data_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/unknown-license-reference.yml",
          "spdx_license_key": "LicenseRef-scancode-unknown-license-reference",
          "spdx_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/unknown-license-reference.LICENSE",
          "start_line": 70,
          "end_line": 70,
          "matched_rule": {
            "identifier": "license-intro_9.RULE",
            "license_expression": "unknown-license-reference",
            "licenses": [
              "unknown-license-reference"
            ],
            "is_license_text": false,
            "is_license_notice": false,
            "is_license_reference": false,
            "is_license_tag": false,
            "is_license_intro": true,
            "matcher": "2-aho",
            "rule_length": 2,
            "matched_length": 2,
            "match_coverage": 100.0,
            "rule_relevance": 11
          }
        },
        {
          "key": "unlicense",
          "score": 50.0,
          "name": "Unlicense",
          "short_name": "Unlicense",
          "category": "Public Domain",
          "is_exception": false,
          "owner": "Unlicense",
          "homepage_url": "http://unlicense.org/",
          "text_url": "https://unlicense.org/",
          "reference_url": "https://scancode-licensedb.aboutcode.org/unlicense",
          "scancode_text_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/unlicense.LICENSE",
          "scancode_data_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/unlicense.yml",
          "spdx_license_key": "Unlicense",
          "spdx_url": "https://spdx.org/licenses/Unlicense",
          "start_line": 70,
          "end_line": 70,
          "matched_rule": {
            "identifier": "spdx_license_id_unlicense_for_unlicense.RULE",
            "license_expression": "unlicense",
            "licenses": [
              "unlicense"
            ],
            "is_license_text": false,
            "is_license_notice": false,
            "is_license_reference": true,
            "is_license_tag": false,
            "is_license_intro": false,
            "matcher": "2-aho",
            "rule_length": 1,
            "matched_length": 1,
            "match_coverage": 100.0,
            "rule_relevance": 50
          }
        },
        {
          "key": "unlicense",
          "score": 16.0,
          "name": "Unlicense",
          "short_name": "Unlicense",
          "category": "Public Domain",
          "is_exception": false,
          "owner": "Unlicense",
          "homepage_url": "http://unlicense.org/",
          "text_url": "https://unlicense.org/",
          "reference_url": "https://scancode-licensedb.aboutcode.org/unlicense",
          "scancode_text_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/unlicense.LICENSE",
          "scancode_data_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/unlicense.yml",
          "spdx_license_key": "Unlicense",
          "spdx_url": "https://spdx.org/licenses/Unlicense",
          "start_line": 70,
          "end_line": 70,
          "matched_rule": {
            "identifier": "unlicense_2.RULE",
            "license_expression": "unlicense",
            "licenses": [
              "unlicense"
            ],
            "is_license_text": false,
            "is_license_notice": false,
            "is_license_reference": true,
            "is_license_tag": false,
            "is_license_intro": false,
            "matcher": "2-aho",
            "rule_length": 3,
            "matched_length": 3,
            "match_coverage": 100.0,
            "rule_relevance": 16
          }
        }
      ],
      "license_expressions": [
        "unknown-license-reference",
        "unlicense",
        "unlicense"
      ],
      "percentage_of_license_text": 0.12,
      "packages": [],
      "scan_errors": []
    }
  ]
```

**Comment by tdruez** [comment] 2021-08-19 04:13
@pombredanne after investigation, the issue is located in getting the file content using the textcode function `numbered_text_lines`.

```
wc -l _decompose_l_u_8hpp_source.html
     100 _decompose_l_u_8hpp_source.html
```

There's actually 100 lines in that file but `numbered_text_lines` returns 286 lines.

```
>>> len(list(numbered_text_lines("_decompose_l_u_8hpp_source.html")))
286
```

A `demarkup` argument is available and seems to solve this https://github.com/nexB/scancode-toolkit/blob/develop/src/textcode/analysis.py#L51
```
>>> len(list(numbered_text_lines("_decompose_l_u_8hpp_source.html", demarkup=True)))
100
```

@pombredanne is it safe to always call with `demarkup=True` without any negative outcomes?

**Comment by pombredanne** [comment] 2021-08-19 09:39
> is it safe to always call numbered_text_lines with demarkup=True without any negative outcomes?

Good catch! ... hum I need to revisit this... the markup contains logical lines (e.g. `<p/>`) and the code may not be correct in this case (and may be others :| ? )

The thing is that there are warts in SCTK:
- license detection, URLs and emails are using demarkup=False ... but it seems the behavior is different
- copyright is using demarkup=True

But digging further... the issue is NOT with  `demarkup`.

The issue is that plain text goes through this process:
https://github.com/nexB/scancode-toolkit/blob/6bf2fd98653f376779ddfa71b567f92366bb4277/src/textcode/analysis.py#L126 

and `break_numbered_unicode_text_lines` actually breaks long lines and creates an artificially higher number of lines... BUT also returns the original line number. See https://github.com/nexB/scancode-toolkit/blob/6bf2fd98653f376779ddfa71b567f92366bb4277/src/textcode/analysis.py#L176  


So things will need to be clarified and cleaned-up in scancode TK.
In the meantime you can use this function to regain one numbered_lines item per physical, original line:
```Python
def rebuild_lines(numbered_lines):
    """
    Yield (line number, text) given an iterator of (line number, line) where
    all text for the same line number is grouped and returned as a single text.
    """
    from itertools import groupby
    for ln, lines_group in groupby(numbered_lines, key=lambda x: x[0]):
        yield ln, ''.join(line for _ln, line in lines_group)
```

**Comment by tdruez** [comment] 2021-08-19 13:23
Fixed in https://github.com/nexB/scancode.io/commit/f8c1a08a30d83ea416aeb1fbd687836efbca2ad6

**Closed by tdruez** 2021-08-19 13:23 UTC
