### ISSUE TITLE
Scan all the "From" sources files that are mapped "To" deployed files 

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#700] opened 2023-04-27 14:21 UTC
When I run a develop_to_deploy pipeline I would like to have all the "From" devel sources files that are mapped a "To" deployed file to be scanned for license/copyright/email/url

**Comment by tdruez** [comment] 2023-05-18 06:35
Duplicate of https://github.com/nexB/scancode.io/issues/676

**Closed by tdruez** 2023-05-18 06:35 UTC
