### ISSUE TITLE
Add support for CycloneDX 1.4 to the "inspect-manifest" pipeline to import the SBOM into a Project

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode.io#583] opened 2023-01-12 16:30 UTC
Add support for CycloneDX 1.4 to the "inspect-manifest" pipeline to import the SBOM into a Project

**Comment by DennisClark** [comment] 2023-01-12 16:33
we need to provide a good example of an SPDX 2.3 import to indicate how this might best be done.

**Comment by pombredanne** [comment] 2023-01-13 08:56
This may depend on https://github.com/CycloneDX/cyclonedx-python-lib/pull/290
@madpah gentle ping

**Comment by tdruez** [comment] 2023-03-13 18:28
@keshav-space re-opening as the `validate_document` function as a dependency on internet access that need to be removed.

To reproduce, turn-off your internet connection and the following unit test will fail:
- test_scanpipe_inspect_manifest_pipeline_cyclonedx_integration_test
- test_scanpipe_cyclonedx_validate_document

The seems to be an issue with the validate_document function. That code and the tests should never depend on having internet connectivity.

**Comment by keshav-space** [comment] 2023-03-14 10:00
@tdruez turns out RefResolver was not using the local file path provided in `base_uri`.
Its been fixed in #634 and now it works offline.

**Closed** 2023-03-14 11:40 UTC
Labels: enhancement, design-needed, high priority

**Comment by tdruez** [comment] 2023-03-14 11:42
@keshav-space fix confirmed, thanks!
